export const SET_STRATEGY_STOCK = 'SET_STRATEGY_STOCK';
export const SET_SHOW_SELECT_STOCK = 'SET_SHOW_SELECT_STOCK';
export const SHOW_NOTES = 'SHOW_NOTES';
export const LOAD_STRATEGY_DATA = 'LOAD_STRATEGY_DATA';
export const LOAD_CANDLESTICK = 'LOAD_CANDLESTICK';
