export type windowsSeriesDataType = {
    "Close" : number, 
    "High": number, 
    "Low": number, 
    "accel_oss": number, 
    "alligator_jaw": number, 
    "alligator_lips": number, 
    "alligator_teeth": number, 
    "ao": number, 
    "atr": number, 
    "boll": number, 
    "boll_lb": number, 
    "boll_ub": number, 
    "date": number, 
    "ema_10": number, 
    "ema_200": number, 
    "ema_50": number, 
    "fractal_highs": number, 
    "fractal_lows": number, 
    "gator_value1": number, 
    "gator_value2": number, 
    "green": number, 
    "ma": number, 
    "ma_div": number, 
    "macd_h": number, 
    "macd_signal": number, 
    "macd_value": number, 
    "momentum": number, 
    "open": number, 
    "rsi_12": number, 
    "rsi_18": number, 
    "rsi_24": number, 
    "rsi_6": number, 
    "sma_10": number, 
    "sma_200": number, 
    "sma_50": number, 
    "smma_200": number, 
    "smma_5": number, 
    "smma_50": number, 
    "ticker_id": number, 
    "trend_close": number, 
    "trend_ma": number, 
    "volume": number
}


//export type windowsSeriesDataKeyType = keyof typeof windowsSeriesDataType;

